### ISSUE TITLE
One of the ansible playbooks is setting the mount targets on the nodes

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#105]
I had updated node 212 but one of the playbooks reset the node back to what's below.
```
172.16.6.6:/home /home nfs defaults 0 0
172.16.0.25:/export/cluster /nfs/cluster nfs defaults,noatime,bg,timeo=100,ac,actimeo=120,cto,rsize=1048576,wsize=1048576,nolock,local_lock=all,mountproto=tcp,sec=sys,_netdev 0 0
172.16.6.6:/data /data nfs defaults 0 0
172.16.4.200:/mnt/nfsshare/exports/data /mnt/ha-nfs/data nfs defaults 0 0
172.16.4.200:/mnt/nfsshare/exports/home /mnt/ha-nfs/home nfs defaults 0 0
172.16.6.6:/data /mnt/fss/data nfs defaults 0 0
172.16.6.6:/home /mnt/fss/home nfs defaults 0 0
172.16.6.6:/data/nix /nix nfs defaults 0 0
```

We need to figure out which playbook or role is changing them to be able to update it or stop it.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

I don't think this is happening any more. Closing.

**Comment by steven-basart** [comment]
We need to make sure this issue doesn't affect the weka mounts.  I don't believe it will but needs investigation. Which playbook is editing the mount targets.

**Comment by andriy-safe-ai** [comment]
This is still happening. The `/etc/fstab` file is still getting updated. 

I'm working on node `35` and the filesystem table has a new entry for the fss: `172.16.6.6:/data /data nfs defaults 0 0`. 
It looks like the fss entry has been re-added with the original mount target. 
This issue should be addressed sooner rather than later since it could affect Weka when we reboot a node.

**Comment by andriy-safe-ai** [comment]
```
# get list of all compute nodes
sudo sinfo -S "%n" -o "%n" | tail -n +2 > compute_nodes

# remove new entry for the fss
pdsh -w ^compute_nodes sudo sed -i '/172\.16\.6\.6:\/data \/data nfs defaults 0 0/d' /etc/fstab
```

**Comment by andriy-safe-ai** [comment]
Solution:

On the bastion node, update the `/etc/ansible/hosts` file and set the `nfs_target_path` variable equal to `/mnt/fss/data`. Remove the incorrect FSS entry from `/etc/fstab` from all nodes. 

Explanation:
The `/etc/fstab` file gets updated when we run the `resize.sh` script. By updating the `nfs_target_path` variable when we add a new node to the cluster the new node will automatically have the FSS mounted to the `/mnt/fss/data` directory which makes adding Weka to the new node simple since we will no longer have to worry about unmounting the FSS. In addition to the new node, the `/etc/fstab` is also updated on existing nodes if the fstab entry is missing for the FSS. After the variable is changed the FSS entry will still get added but the entry will be to mount the FSS to `/mnt/fss/data` so the FSS will no longer interfere with Weka which is mounted to `/data`. We will also be able to remove the mount targets we added for the FSS but I will do this in a separate GitHub issues as part of the Weka Migration Epic.

**Comment by andriy-safe-ai** [comment]
Updated the following nodes in production:
- bastion
- backup
- login
- 35
- 48
- 76
- 84
- 102
- 153
- 166
- 171
- 269
- 323
- 363
- 365
- 408
- 485
- 537
- 587
- 605
- 618
- 719
- 733
- 746
- 800
- 863
- 870
- 871
- 891
- 907
- 912
- 918
- 975
- 978
- 990

Closing.
