### ISSUE TITLE
Monitor nix usage

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#111]
We don't know if users are using nix or not.  We can ask a few users to try it out (internal CAIS users first).

**Comment by andriy-safe-ai** [comment]
@steven-basart 
Used the following bash script to view which users have installed packages through Nix and there quantity:
```
#!/bin/bash

for dir in /data/*
do
        if [ -d "$dir/.local/state/nix/profiles/profile" ]
        then
                echo "$dir -> $(sudo cat $dir/.nix-profile/manifest.json | jq '.elements | length')"
        fi
done
```

Output:
```
/data/andriy -> 2
cat: /data/karina_belokapov/.nix-profile/manifest.json: No such file or directory
/data/karina_belokapov -> 
/data/natli -> 4
cat: /data/pranav_gade/.nix-profile/manifest.json: No such file or directory
/data/pranav_gade -> 
/data/rumiah_kessel -> 4
```

Analysis:
Not including Rumiah and myself, we have three users that have installed packages through Nix. Surprisingly, two of the users installed packages using a method for which we did not provide documentation. For example, instead of installing the `hello` package with `nix-install hello` or `nix profile install nixpkgs.hello`, both of which us the `nix` command, they instead used `nix-env -iA nixpkgs.hello` which we wanted to move away from. The `manifest.json` is only created when the `nix` command is used. Using `nix-env` created a `manifest.nix` file that has a different structure. I manually checked these users and found that Karina installed only 1 package and Pranav has installed 4 packages. 

Overall, Nix hasn't seen wide adoption and the most of the users that have used Nix haven't used it the way we've intended.

**Comment by andriy-safe-ai** [comment]
Nat is very happy with Nix. Closing.
