### ISSUE TITLE
Alerting

### ISSUE THREAD

**Issue by trent-safe-ai** [centerforaisafety/cerberus-cluster#131]
Determine what we would like alerted on via slack and email from alert manager/prometheus/Loki

Examples
* Slurm nodes go into drain or are no longer accessible.
* usage total exceeds current expected capacity in HPC cluster
* any outages of sites and services hosted in Prod Kubernetes
* alerts relating to any issues in OCI

**Comment by rumiahkessel** [comment]
We just finished setting up slack notifications for node down, drain, slurmctld related things etc. So if you want to switch to using grafana for all or just the ones not covered below.

backup_slurmctld_assumed_control *
backup_slurmctld_failure *
backup_slurmctld_resumed_operation *
node_down*
node_drain*
node_fail*(for some reason says drain instead of fail. Seems to be because this is considered a transient state)
node_up*
primary_database_failure
primary_database_resumed_operation *
primary_slurmctld_acct_buffer_full
primary_slurmctld_failure *
primary_slurmctld_resumed_control *
primary_slurmctld_resumed_operation *
primary_slurmdbd_failure
primary_slurmdbd_resumed_operation *

**Comment by trent-safe-ai** [comment]
@rumiahkessel did this one closing.
