### ISSUE TITLE
VS Code support

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#81]
See here: https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev
Needs more resources to be filled out as well.

**Comment by trent-safe-ai** [comment]
@steven-basart what is the ask on this issue? Do we have action items that need done?

**Comment by rumiahkessel** [comment]
From my investigation I do not think there is any immediate action needed for vscode performance. The extensions our users are using are within our operating capabilities and each user appears to be using a reasonable amount of resources. Unfortunately the resources that suggested ways reduce the performance impact of the server itself without impacting functionality were proven to be misleading (outdated or shown to be faulty by the microsoft vscode-server team). 

If we notice performance problems in the future, I detail how to address performance in each of these areas below, but can easily ask users to stop using ai autocomplete tools and to restrict memory usage per user to about 2 or 3 GB as this would limit the number of extensions they can use and restrict the size of their working directory. 

CPU:
* This is mainly determined by the extension being used and the most common highest cost process is pylance but only at 2% of one of the cores (well within reasonable ranges). 
* Github copilot and other ai driven autocompletes have much higher performance costs that we can consider restricting. I found github copilot to at times be using in the 30%+ range for longer periods of time.
* Pylance occasionally spikes higher than this but only for very short periods of time <10 seconds and thus I think is not a concern. From my experimentation on dev this appears to be caused by saving a python file and only lasts for one htop refresh.

Memory:
* Best way to address performance issues would be to limit the amount of memory each user can use on login (2 or 3GB for extended time) as it is almost directly related to each of the different ways they can misuse vscode-server seen below:
* This is entirely decided by the extensions installed. Should encourage users to limit the number of extensions installed as much as possible and be very selective. 
* Can also limit the usage by using smaller working directories. Prevent/encourage users to not use ~ as the working directory and have a folder or file for each project. This can cut memory usage per user by a significant amount depending on the size of the overall directory and the smaller directory (tested on dev). 
* Many extensions use little to no memory < 0.1% (60M), but a couple extensions per use use more (pylance, vscode server itself, and others that have hashed names). . For example the dist_training.py with pylance will use about 0.3% memory (218M) but 10 dist_training.py will use 0.5%  (~300M) per process. It doesn’t have a clear growth relationship and there is some caching optimization that reduces this cost slowly for a few minutes after new files are made, but can be avoided by using much smaller working directories. However, by far the biggest cost is just the number of extensions installed
* Currently our largest users on prod use ~2GB of memory for vscode. They use a large amount of virtual address space though and vscode-server for some is using 11.3G of virtual memory.
Storage:
* Simple vscode server with minimal python extensions uses 454M. Need to watch for this increasing as it has its own logs
    * ms-python.isort
    * ms-python.python
    * ms-python.vscode-pylance
    * ms-toolsai.jupyter
    * ms-toolsai.jupyter-renderers
    * ms-toolsai.vscode-jupyter-cell-tags
    * ms-toolsai.vscode-jupyter-slideshow
* With new mount targets there is no perceivable io latency on the login node and viewing ios through iotop shows very little usage by vscode (only used when saving or opening a file or the like). Reasonable and doesn’t seem to be a problem.
    * Github copilot may be using more ios but I did not have the tool installed at the time, but the command it was using was greping the file system, so was likely performing ios.

**Comment by rumiahkessel** [comment]
If you would like I can add instructions to cluster docs explaining how to setup the extension. It is fairly simple, but there is a setting that improves security when you have multiple users connecting, so we should have instructions asking users to enable this setting and encourage current users to switch to it.

**Comment by steven-basart** [comment]
> If you would like I can add instructions to cluster docs explaining how to setup the extension. It is fairly simple, but there is a setting that improves security when you have multiple users connecting, so we should have instructions asking users to enable this setting and encourage current users to switch to it.

This last comment is a bit unclear to me? By this extension which one are you referring to? Also what's "this setting"?

**Comment by rumiahkessel** [comment]
Sorry about that. I ended up adding instructions for all of this in the pr. The extension is the Remote SSH extension which is what the vast majority of our users are using to do remote development. The setting switches from listening to a port to listening on socket. Simple but better.
